DROP TABLE IF EXISTS TBL_TASKS;
  
CREATE TABLE TBL_TASK (
  taskId INT AUTO_INCREMENT  PRIMARY KEY,
  userId INT NOT NULL,
  task VARCHAR(250) NOT NULL,
  description VARCHAR(250) NOT NULL,
  lastUpdated DATE,
  isTaskCompleted BOOLEAN
);